data <- read.csv("topicmodels.csv")
print(data)
df <- data.frame(data)
print(df)
library("texreg")
install.packages('broom')
texreg(df)
install.packages('Hmisc')
library(Hmisc)
latex(df, file="df.tex")           
